# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hash_sign_pb2 as hash__sign__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hash_sign_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HashSignServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeAndSignHash = channel.unary_unary(
                '/forensicchain.hashsign.HashSignService/ComputeAndSignHash',
                request_serializer=hash__sign__pb2.ArtifactHashRequest.SerializeToString,
                response_deserializer=hash__sign__pb2.IntegrityProofResponse.FromString,
                _registered_method=True)
        self.RecomputeHash = channel.unary_unary(
                '/forensicchain.hashsign.HashSignService/RecomputeHash',
                request_serializer=hash__sign__pb2.ArtifactHashRequest.SerializeToString,
                response_deserializer=hash__sign__pb2.HashResponse.FromString,
                _registered_method=True)
        self.VerifySignature = channel.unary_unary(
                '/forensicchain.hashsign.HashSignService/VerifySignature',
                request_serializer=hash__sign__pb2.SignatureVerifyRequest.SerializeToString,
                response_deserializer=hash__sign__pb2.SignatureVerifyResponse.FromString,
                _registered_method=True)


class HashSignServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComputeAndSignHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecomputeHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifySignature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HashSignServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeAndSignHash': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeAndSignHash,
                    request_deserializer=hash__sign__pb2.ArtifactHashRequest.FromString,
                    response_serializer=hash__sign__pb2.IntegrityProofResponse.SerializeToString,
            ),
            'RecomputeHash': grpc.unary_unary_rpc_method_handler(
                    servicer.RecomputeHash,
                    request_deserializer=hash__sign__pb2.ArtifactHashRequest.FromString,
                    response_serializer=hash__sign__pb2.HashResponse.SerializeToString,
            ),
            'VerifySignature': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifySignature,
                    request_deserializer=hash__sign__pb2.SignatureVerifyRequest.FromString,
                    response_serializer=hash__sign__pb2.SignatureVerifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forensicchain.hashsign.HashSignService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forensicchain.hashsign.HashSignService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HashSignService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComputeAndSignHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forensicchain.hashsign.HashSignService/ComputeAndSignHash',
            hash__sign__pb2.ArtifactHashRequest.SerializeToString,
            hash__sign__pb2.IntegrityProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecomputeHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forensicchain.hashsign.HashSignService/RecomputeHash',
            hash__sign__pb2.ArtifactHashRequest.SerializeToString,
            hash__sign__pb2.HashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifySignature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forensicchain.hashsign.HashSignService/VerifySignature',
            hash__sign__pb2.SignatureVerifyRequest.SerializeToString,
            hash__sign__pb2.SignatureVerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
