# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hash_sign.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hash_sign.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fhash_sign.proto\x12\x16\x66orensicchain.hashsign\"\x8c\x01\n\x13\x41rtifactHashRequest\x12\x13\n\x0b\x61rtifact_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61se_id\x18\x02 \x01(\t\x12\x11\n\tfile_path\x18\x03 \x01(\t\x12\x11\n\tfile_name\x18\x04 \x01(\t\x12\x11\n\tfile_size\x18\x05 \x01(\x03\x12\x16\n\x0ehash_algorithm\x18\x06 \x01(\t\"\xee\x01\n\x16IntegrityProofResponse\x12\x13\n\x0b\x61rtifact_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61se_id\x18\x02 \x01(\t\x12\x16\n\x0ehash_algorithm\x18\x03 \x01(\t\x12\x12\n\nhash_value\x18\x04 \x01(\t\x12\x1b\n\x13signature_algorithm\x18\x05 \x01(\t\x12\x17\n\x0fsignature_value\x18\x06 \x01(\t\x12\x11\n\tsigner_id\x18\x07 \x01(\t\x12\x11\n\tsigned_at\x18\x08 \x01(\t\x12\x0f\n\x07success\x18\t \x01(\x08\x12\x15\n\rerror_message\x18\n \x01(\t\"w\n\x0cHashResponse\x12\x13\n\x0b\x61rtifact_id\x18\x01 \x01(\t\x12\x16\n\x0ehash_algorithm\x18\x02 \x01(\t\x12\x12\n\nhash_value\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x15\n\rerror_message\x18\x05 \x01(\t\"w\n\x16SignatureVerifyRequest\x12\x13\n\x0b\x61rtifact_id\x18\x01 \x01(\t\x12\x12\n\nhash_value\x18\x02 \x01(\t\x12\x17\n\x0fsignature_value\x18\x03 \x01(\t\x12\x1b\n\x13signature_algorithm\x18\x04 \x01(\t\"o\n\x17SignatureVerifyResponse\x12\x13\n\x0b\x61rtifact_id\x18\x01 \x01(\t\x12\x17\n\x0fsignature_valid\x18\x02 \x01(\x08\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12\x15\n\rerror_message\x18\x04 \x01(\t2\xdc\x02\n\x0fHashSignService\x12q\n\x12\x43omputeAndSignHash\x12+.forensicchain.hashsign.ArtifactHashRequest\x1a..forensicchain.hashsign.IntegrityProofResponse\x12\x62\n\rRecomputeHash\x12+.forensicchain.hashsign.ArtifactHashRequest\x1a$.forensicchain.hashsign.HashResponse\x12r\n\x0fVerifySignature\x12..forensicchain.hashsign.SignatureVerifyRequest\x1a/.forensicchain.hashsign.SignatureVerifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hash_sign_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTIFACTHASHREQUEST']._serialized_start=44
  _globals['_ARTIFACTHASHREQUEST']._serialized_end=184
  _globals['_INTEGRITYPROOFRESPONSE']._serialized_start=187
  _globals['_INTEGRITYPROOFRESPONSE']._serialized_end=425
  _globals['_HASHRESPONSE']._serialized_start=427
  _globals['_HASHRESPONSE']._serialized_end=546
  _globals['_SIGNATUREVERIFYREQUEST']._serialized_start=548
  _globals['_SIGNATUREVERIFYREQUEST']._serialized_end=667
  _globals['_SIGNATUREVERIFYRESPONSE']._serialized_start=669
  _globals['_SIGNATUREVERIFYRESPONSE']._serialized_end=780
  _globals['_HASHSIGNSERVICE']._serialized_start=783
  _globals['_HASHSIGNSERVICE']._serialized_end=1131
# @@protoc_insertion_point(module_scope)
