location = /internal/auth/validate {
    internal;

    set $auth_svc "auth-service:8006";
    proxy_pass              http://$auth_svc/internal/auth/validate;
    proxy_pass_request_body off;
    proxy_set_header        Content-Length    "";
    proxy_set_header        Authorization     $http_authorization;
    proxy_set_header        X-Original-URI    $request_uri;
    proxy_set_header        X-Original-Method $request_method;

    proxy_http_version 1.1;
    proxy_read_timeout 10s;
}
