# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ledger_pb2 as ledger__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ledger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LedgerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AppendProofRecord = channel.unary_unary(
                '/forensicchain.ledger.LedgerService/AppendProofRecord',
                request_serializer=ledger__pb2.ProofRecordRequest.SerializeToString,
                response_deserializer=ledger__pb2.ProofRecordResponse.FromString,
                _registered_method=True)
        self.AppendVerificationRecord = channel.unary_unary(
                '/forensicchain.ledger.LedgerService/AppendVerificationRecord',
                request_serializer=ledger__pb2.VerificationRecordRequest.SerializeToString,
                response_deserializer=ledger__pb2.ProofRecordResponse.FromString,
                _registered_method=True)
        self.GetProofByArtifactId = channel.unary_unary(
                '/forensicchain.ledger.LedgerService/GetProofByArtifactId',
                request_serializer=ledger__pb2.ArtifactProofRequest.SerializeToString,
                response_deserializer=ledger__pb2.ArtifactIntegrityProofResponse.FromString,
                _registered_method=True)
        self.ValidateLedgerChain = channel.unary_unary(
                '/forensicchain.ledger.LedgerService/ValidateLedgerChain',
                request_serializer=ledger__pb2.ValidateLedgerRequest.SerializeToString,
                response_deserializer=ledger__pb2.ValidateLedgerResponse.FromString,
                _registered_method=True)


class LedgerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AppendProofRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendVerificationRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProofByArtifactId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateLedgerChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LedgerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AppendProofRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendProofRecord,
                    request_deserializer=ledger__pb2.ProofRecordRequest.FromString,
                    response_serializer=ledger__pb2.ProofRecordResponse.SerializeToString,
            ),
            'AppendVerificationRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendVerificationRecord,
                    request_deserializer=ledger__pb2.VerificationRecordRequest.FromString,
                    response_serializer=ledger__pb2.ProofRecordResponse.SerializeToString,
            ),
            'GetProofByArtifactId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProofByArtifactId,
                    request_deserializer=ledger__pb2.ArtifactProofRequest.FromString,
                    response_serializer=ledger__pb2.ArtifactIntegrityProofResponse.SerializeToString,
            ),
            'ValidateLedgerChain': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateLedgerChain,
                    request_deserializer=ledger__pb2.ValidateLedgerRequest.FromString,
                    response_serializer=ledger__pb2.ValidateLedgerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'forensicchain.ledger.LedgerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('forensicchain.ledger.LedgerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LedgerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AppendProofRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forensicchain.ledger.LedgerService/AppendProofRecord',
            ledger__pb2.ProofRecordRequest.SerializeToString,
            ledger__pb2.ProofRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendVerificationRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forensicchain.ledger.LedgerService/AppendVerificationRecord',
            ledger__pb2.VerificationRecordRequest.SerializeToString,
            ledger__pb2.ProofRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProofByArtifactId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forensicchain.ledger.LedgerService/GetProofByArtifactId',
            ledger__pb2.ArtifactProofRequest.SerializeToString,
            ledger__pb2.ArtifactIntegrityProofResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateLedgerChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/forensicchain.ledger.LedgerService/ValidateLedgerChain',
            ledger__pb2.ValidateLedgerRequest.SerializeToString,
            ledger__pb2.ValidateLedgerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
