import { useState } from 'react'
import { useParams } from 'react-router-dom'
import {
  downloadReportUrl,
  generateReport,
  verifyReport,
  type Report,
  type ReportVerification,
} from '../api/reports'
import Layout from '../components/Layout'

export default function ReportPage() {
  const { artifactId } = useParams<{ artifactId: string }>()

  const [report, setReport] = useState<Report | null>(null)
  const [verification, setVerification] = useState<ReportVerification | null>(null)
  const [generating, setGenerating] = useState(false)
  const [verifying, setVerifying] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function handleGenerate() {
    if (!artifactId) return
    setGenerating(true)
    setError(null)
    setVerification(null)
    try {
      const r = await generateReport(artifactId)
      setReport(r)
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Report generation failed')
    } finally {
      setGenerating(false)
    }
  }

  async function handleVerify() {
    if (!report) return
    setVerifying(true)
    try {
      const v = await verifyReport(report.report_id)
      setVerification(v)
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Verification failed')
    } finally {
      setVerifying(false)
    }
  }

  return (
    <Layout>
      <div className="max-w-2xl space-y-6">
        <div className="flex items-start justify-between gap-4">
          <h1 className="text-2xl font-bold text-gray-900">Forensic Report</h1>
          <span className="text-xs text-gray-400 font-mono mt-1 break-all">{artifactId}</span>
        </div>

        {error && (
          <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">
            {error}
          </div>
        )}

        <button
          onClick={handleGenerate}
          disabled={generating}
          className="rounded-md bg-indigo-600 px-5 py-2 text-sm font-semibold text-white hover:bg-indigo-500 disabled:opacity-50 transition-colors"
        >
          {generating ? 'Generating PDF…' : 'Generate new report'}
        </button>

        {report && (
          <section className="rounded-xl border border-gray-200 bg-white p-5 space-y-4">
            <h2 className="font-semibold text-gray-800">Report metadata</h2>

            <dl className="grid grid-cols-2 gap-x-6 gap-y-2 text-sm">
              {(
                [
                  ['Report ID', report.report_id],
                  ['Generated by', report.generated_by],
                  ['Generated at', report.generated_at?.slice(0, 19).replace('T', ' ')],
                  ['Format', report.format],
                ] as [string, string | null | undefined][]
              ).map(([label, value]) => (
                <div key={label}>
                  <dt className="text-gray-400">{label}</dt>
                  <dd className="text-gray-700 font-mono text-xs truncate">{value ?? '—'}</dd>
                </div>
              ))}
            </dl>

            <details className="text-xs">
              <summary className="cursor-pointer text-gray-400 hover:text-gray-600">
                Raw JSON
              </summary>
              <pre className="mt-2 overflow-auto whitespace-pre-wrap break-all text-gray-600 bg-gray-50 rounded-md p-3">
                {JSON.stringify(report, null, 2)}
              </pre>
            </details>

            <div className="flex flex-wrap gap-3">
              <a
                href={downloadReportUrl(report.report_id)}
                target="_blank"
                rel="noreferrer"
                className="rounded-md bg-emerald-600 px-4 py-1.5 text-sm font-medium text-white hover:bg-emerald-500 transition-colors"
              >
                Download PDF
              </a>
              <button
                onClick={handleVerify}
                disabled={verifying}
                className="rounded-md bg-gray-100 px-4 py-1.5 text-sm font-medium text-gray-800 hover:bg-gray-200 disabled:opacity-50 transition-colors"
              >
                {verifying ? 'Verifying…' : 'Verify report integrity'}
              </button>
            </div>

            {verification && (
              <div
                className={`rounded-lg p-3 text-sm ${
                  verification.report_valid
                    ? 'bg-emerald-50 text-emerald-800'
                    : 'bg-red-50 text-red-800'
                }`}
              >
                <p className="font-semibold">
                  {verification.report_valid ? 'Report VALID ✓' : 'Report TAMPERED ✗'}
                </p>
                <pre className="mt-2 text-xs overflow-auto whitespace-pre-wrap break-all">
                  {JSON.stringify(verification, null, 2)}
                </pre>
              </div>
            )}
          </section>
        )}
      </div>
    </Layout>
  )
}
